apiVersion: v1
data:
  password: ""
  username: cm9vdA==
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: ml-pipeline
    app.kubernetes.io/name: kubeflow-pipelines
  name: mysql-secret-db2h2gbg52
  namespace: kubeflow
type: Opaque
