apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tf-job-operator
    app.kubernetes.io/component: tfjob
    app.kubernetes.io/name: tf-job-operator
    kustomize.component: tf-job-operator
  name: tf-job-operator
  namespace: kubeflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tf-job-operator
      app.kubernetes.io/component: tfjob
      app.kubernetes.io/name: tf-job-operator
      kustomize.component: tf-job-operator
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: tf-job-operator
        app.kubernetes.io/component: tfjob
        app.kubernetes.io/name: tf-job-operator
        kustomize.component: tf-job-operator
        name: tf-job-operator
    spec:
      containers:
      - args:
        - -monitoring-port=8443
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: public.ecr.aws/j1r0q0g6/training/tf-operator:cd2fc1ff397b1f349f68524f4abd5013a32e3033
        name: tf-job-operator
      serviceAccountName: tf-job-operator
