apiVersion: v1
data:
  ingressGateway: '"kubeflow-gateway.kubeflow",'
kind: ConfigMap
metadata:
  labels:
    app: kfserving
    app.kubernetes.io/component: kfserving
    app.kubernetes.io/name: kfserving
    kustomize.component: kfserving
  name: kfserving-config
  namespace: kubeflow
