apiVersion: v1
kind: Service
metadata:
  labels:
    app: kfserving
    app.kubernetes.io/component: kfserving
    app.kubernetes.io/name: kfserving
    kustomize.component: kfserving
  name: kfserving-webhook-server-service
  namespace: kubeflow
spec:
  ports:
  - port: 443
    targetPort: webhook-server
  selector:
    app: kfserving
    app.kubernetes.io/component: kfserving
    app.kubernetes.io/name: kfserving
    control-plane: kfserving-controller-manager
    kustomize.component: kfserving
