apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: kf-ref2-admin@jamxl-kfp-dev.iam.gserviceaccount.com
  labels:
    kustomize.component: profiles
  name: profiles-controller-service-account
  namespace: kubeflow
